name: Quick Test

on: push

jobs:
  default:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [2.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set environment variables
      if: ${{ runner.os != 'Windows' }}
      run: |
        if [[ ${{ runner.os }} == macOS ]]; then
        echo "LDFLAGS=-L/usr/local/opt/openssl@1.1/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/usr/local/opt/openssl@1.1/include" >> $GITHUB_ENV
        fi
    - name: Install apt dependencies
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get install -yq --no-install-suggests --no-install-recommends \
        build-essential libcap-dev libssl-dev python-all-dev python-qt4 tor xvfb
    - name: Install brew dependencies
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install tor
        brew services start tor
    - name: Install windows dependencies
      if: ${{ runner.os == 'Windows' }}
      run: |
        Start-Job -Name WebReq -ScriptBlock {
        Invoke-WebRequest -Uri "https://github.com/Bitmessage/ThirdPartyLibraries/blob/master/Win64OpenSSL-1_0_2t.exe?raw=true" -OutFile "Win64OpenSSL-1_0_2t.exe"
        Invoke-WebRequest -Uri "https://web.archive.org/web/20190720195601/https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi" -OutFile "VCForPython27.msi"
        }
        Wait-Job -Name WebReq
        Start-Process -FilePath Win64OpenSSL-1_0_2t.exe -ArgumentList '/q /norestart /silent /verysilent /sp- /suppressmsgboxes /dir=C:\OpenSSL-Win64' -Wait
        Start-Process -FilePath VCForPython27.msi -ArgumentList '/qn /norestart'  -Wait
        echo "OPENSSL_DIR=c:\\OpenSSL-Win64" >> $GITHUB_ENV
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python setup.py install
    - name: Test
      run: |
        export PYTHONWARNINGS=all
        python checkdeps.py
        python src/bitmessagemain.py -t
        python -bm tests
