name: Quick Test

on: push

jobs:
  default:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install windows dependencies
      if: ${{ runner.os == 'Windows' }}
      run: |
        Start-Job -Name WebReq -ScriptBlock {
        Invoke-WebRequest -Uri "https://github.com/Bitmessage/ThirdPartyLibraries/blob/master/Win64OpenSSL-1_0_2t.exe?raw=true" -OutFile "Win64OpenSSL-1_0_2t.exe"
        Invoke-WebRequest -Uri "https://www.python.org/ftp/python/2.7.17/python-2.7.17.msi"
        Invoke-WebRequest -Uri "https://web.archive.org/web/20190720195601/https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi"
        }
        Wait-Job -Name WebReq
        Start-Process -FilePath Win64OpenSSL-1_0_2t.exe -ArgumentList '/q /norestart /silent /verysilent /sp- /suppressmsgboxes /dir=C:\OpenSSL-Win64' -Wait
        Start-Process msiexec -ArgumentList '-i python-2.7.17.msi /qn /norestart'  -Wait
        Start-Process msiexec -ArgumentList '-i VCForPython27.msi /qn /norestart'  -Wait
    - name: Install python dependencies
      env:
        OPENSSL_DIR: "c:\\OpenSSL-Win64"
      run: |
        python2 -m pip install --upgrade pip
        python2 -m pip install -r requirements.txt
        python2 -m pip install msgpack-python .[json,xml]
        python2 setup.py egg_info
        python2 -m pip install -I pyinstaller==3.5
    - name: Build
      run: |
        pyinstaller packages/pyinstaller/bitmessagemain.spec
