name: Test Windows 64bit exe

on: push

jobs:
  build-exe:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install apt dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -yq --no-install-recommends \
        build-essential libcap-dev libssl-dev python-all-dev \
        wine-stable winetricks wine32 wine64 mingw-w64 xvfb
    - name: Build
      id: build
      run: |
        xvfb-run -a buildscripts/winbuild.sh
        echo "::set-output name=asset_path::packages/pyinstaller/dist/*.exe"
    - name: Create build-output artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: ${{ steps.build.outputs.asset_path }}

  test-exe:

    runs-on: windows-2019
    needs: build-exe

    steps:
    - name: Download
      uses: actions/download-artifact@v3
      with:
        name: build-output
    - name: Test
      run: .\Bitmessage_x64_0.6.3.2.exe -t
